Final commit
nehalskdev/Cat-food-website pull request #1
Opened 2024-03-09 09:56 UTC by nehalskdev

2024-03-09 11:22 UTC, SaadMahi commented
try to fix the height of home page in 100vh

2024-03-09 13:57 UTC, anask601 reviewed
@nehalskdev Unintended horizontal scrolling and empty white space from the right are happening.

2024-03-10 08:30 UTC, nehalskdev commented
@anask601 please check is the white space gone?

2024-03-10 11:56 UTC, ManSOorcode requested changes

2024-03-10 11:56 UTC, ManSOorcode commented on index.html
> +          <img src="assets/bonkers.svg" alt="Text that says bonkers" />
manage it's width according to small screen

2024-03-11 09:27 UTC, SaadMahi commented
LGTM 👍

2024-03-14 08:39 UTC, merged